### 用来向认证中心获取授权
GET http://localhost:8082/sso/oauth/authorize?client_id=client1&client_secret=secret&response_type=code&scope=all&redirect_uri=http://www.baidu.com
Accept: application/json

### 授权码模式获取token
GET http://localhost:8082/sso/oauth/token?client_id=client1&client_secret=secret&code=rqqFUg&grant_type=authorization_code&scope=all&redirect_uri=http://www.baidu.com
Accept: application/json

### 密码模式获取token
GET http://localhost:8082/sso/oauth/token?client_id=client1&client_secret=secret&username=admin&password=123456&grant_type=password
Accept: application/json

### 客户端模式
GET http://localhost:8082/sso/oauth/token?client_id=client1&client_secret=secret&grant_type=client_credentials
Accept: application/json

### 简化模式，跳转到登录页面，登陆成功后便可获取token
GET http://localhost:8082/sso/oauth/authorize?client_id=client1&client_secret=secret&response_type=token&redirect_uri=http://www.baidu.com
Accept: application/json

### 刷新token
GET http://localhost:8082/sso/oauth/token?client_id=client1&client_secret=secret&grant_type=refresh_token&refresh_token=e3ff8b17-9c68-40cd-bd2a-576df8689fb8
Accept: application/json